service: cake-order

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs10.x

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource: 
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/ordersTable
    - Effect: Allow
      Action:
        - kinesis:PutRecord
      Resource:
        - arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events 
      

functions:
  createOrder:
    handler: handler.createOrder
    events:
      - http:
          path: /order
          method: post
          cors: false
          private: false
    # These are just enviormental variables.... Wow      
    environment:
      orderTableName: ordersTable
      orderStreamName: order-events

  orderFullfllMent:
    handler: handler.orderFullfillment
    events:
      - http: 
          path: /order/fullfill
          method: post
          cors: false
          private: false

resources:
  Resources:
    orderEventsStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: order-events
        ShardCount: 1
    orderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ordersTable
        AttributeDefinitions:
          - AttributeName: "orderId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "orderId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST